name: Publish Packages
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish-rust:
    runs-on: ubuntu-latest
    environment: release # Optional: for enhanced security
    permissions:
      contents: read
      id-token: write # Required for OIDC token exchange
    steps:
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          toolchain: nightly,stable
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: rust-lang/crates-io-auth-action@e919bc7605cde86df457cf5b93c5e103838bd879
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-npm:
    runs-on: ubuntu-latest
    environment: release # Optional: for enhanced security
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - run: npm publish
